import type { Metadata } from "next";

import "./globals.css";
import { Providers } from "@/lib/Providers";

export const metadata: Metadata = {
  title: "Green Leaf",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
